version: "3.9"
services:
  mongo:
    image: mongo:7
    container_name: helpdesk-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: helpdesk-backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: helpdesk-frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mongo-data:
